# Generated by Django 6.0.2 on 2026-02-06 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetypeofpet',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_type_of_pet', to='pets.service'),
        ),
        migrations.AlterField(
            model_name='servicetypeofpet',
            name='type_of_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_type_of_pet', to='pets.typeofpet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
